create table tab_cliente (
id_cliente integer generated by default as identity,
dt_aniversario date,
nome_cidade varchar(255),
nome_completo varchar(255),
renda_media float(53),
primary key (id_cliente)
);